drop extension if exists "pg_net";


  create table "public"."approval_comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "document_supervisor_id" uuid not null default gen_random_uuid(),
    "comment" text,
    "created_by" uuid not null default gen_random_uuid(),
    "status" character varying not null
      );


alter table "public"."approval_comments" enable row level security;


  create table "public"."categories" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "color" character varying not null,
    "user_id" uuid not null
      );


alter table "public"."categories" enable row level security;


  create table "public"."document_supervisors" (
    "id" uuid not null default gen_random_uuid(),
    "file_id" uuid not null default gen_random_uuid(),
    "supervisor_id" uuid not null default gen_random_uuid(),
    "status" character varying not null,
    "invited_by" uuid not null default gen_random_uuid(),
    "invited_at" timestamp with time zone not null,
    "responded_at" timestamp with time zone
      );


alter table "public"."document_supervisors" enable row level security;


  create table "public"."file_permissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean not null default false,
    "permission_type" character varying not null,
    "granted_by" uuid not null default gen_random_uuid(),
    "file_id" uuid not null default gen_random_uuid(),
    "granted_to" uuid not null default gen_random_uuid()
      );


alter table "public"."file_permissions" enable row level security;


  create table "public"."file_revisions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "file_id" uuid not null default gen_random_uuid(),
    "version_number" bigint not null,
    "storage_key" character varying not null,
    "file_hash" character varying not null,
    "size" double precision not null,
    "uploaded_at" timestamp with time zone
      );


alter table "public"."file_revisions" enable row level security;


  create table "public"."files" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "user_id" uuid not null default gen_random_uuid(),
    "folder_id" uuid not null default gen_random_uuid(),
    "name" character varying not null,
    "created_by" character varying not null,
    "updated_by" character varying,
    "extension" character varying not null,
    "size" double precision not null default '0'::double precision,
    "path" character varying not null,
    "is_favourite" boolean not null default false,
    "is_deleted" boolean not null default false,
    "category_id" uuid
      );


alter table "public"."files" enable row level security;


  create table "public"."folder_permissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "folder_id" uuid not null default gen_random_uuid(),
    "granted_to" uuid not null default gen_random_uuid(),
    "granted_by" uuid not null default gen_random_uuid(),
    "permission_type" character varying not null,
    "is_active" boolean not null default true
      );


alter table "public"."folder_permissions" enable row level security;


  create table "public"."folders" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null default gen_random_uuid(),
    "name" character varying not null default ''::character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "created_by" character varying not null,
    "updated_by" character varying,
    "path" character varying not null,
    "is_favourite" boolean not null default false,
    "parent_id" uuid,
    "is_deleted" boolean not null default false
      );


alter table "public"."folders" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "username" character varying not null default ''::character varying,
    "is_active" boolean not null default true,
    "deleted_at" timestamp with time zone,
    "home_folder_id" uuid not null
      );


alter table "public"."profiles" enable row level security;


  create table "public"."word_collaboration_documents" (
    "id" uuid not null default gen_random_uuid(),
    "file_id" uuid not null,
    "state" jsonb not null,
    "version_number" integer not null default 1,
    "updated_at" timestamp with time zone not null default now(),
    "updated_by" uuid
      );


alter table "public"."word_collaboration_documents" enable row level security;


  create table "public"."word_collaboration_events" (
    "id" uuid not null default gen_random_uuid(),
    "file_id" uuid not null,
    "created_by" uuid not null,
    "event_type" character varying not null,
    "payload" jsonb not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."word_collaboration_events" enable row level security;


  create table "public"."word_collaboration_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "file_id" uuid not null,
    "user_id" uuid not null,
    "connection_id" character varying not null,
    "cursor_state" jsonb,
    "selection_state" jsonb,
    "is_active" boolean not null default true,
    "last_seen_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."word_collaboration_sessions" enable row level security;

CREATE UNIQUE INDEX approval_comment_pkey ON public.approval_comments USING btree (id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX document_supervisor_pkey ON public.document_supervisors USING btree (id);

CREATE UNIQUE INDEX file_permissions_pkey ON public.file_permissions USING btree (id);

CREATE UNIQUE INDEX file_revisions_pkey ON public.file_revisions USING btree (id);

CREATE UNIQUE INDEX files_pkey ON public.files USING btree (id);

CREATE UNIQUE INDEX folder_permissions_pkey ON public.folder_permissions USING btree (id);

CREATE UNIQUE INDEX folder_pkey ON public.folders USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX word_collaboration_documents_pkey ON public.word_collaboration_documents USING btree (id);

CREATE UNIQUE INDEX word_collaboration_events_pkey ON public.word_collaboration_events USING btree (id);

CREATE UNIQUE INDEX word_collaboration_sessions_pkey ON public.word_collaboration_sessions USING btree (id);

alter table "public"."approval_comments" add constraint "approval_comment_pkey" PRIMARY KEY using index "approval_comment_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."document_supervisors" add constraint "document_supervisor_pkey" PRIMARY KEY using index "document_supervisor_pkey";

alter table "public"."file_permissions" add constraint "file_permissions_pkey" PRIMARY KEY using index "file_permissions_pkey";

alter table "public"."file_revisions" add constraint "file_revisions_pkey" PRIMARY KEY using index "file_revisions_pkey";

alter table "public"."files" add constraint "files_pkey" PRIMARY KEY using index "files_pkey";

alter table "public"."folder_permissions" add constraint "folder_permissions_pkey" PRIMARY KEY using index "folder_permissions_pkey";

alter table "public"."folders" add constraint "folder_pkey" PRIMARY KEY using index "folder_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."word_collaboration_documents" add constraint "word_collaboration_documents_pkey" PRIMARY KEY using index "word_collaboration_documents_pkey";

alter table "public"."word_collaboration_events" add constraint "word_collaboration_events_pkey" PRIMARY KEY using index "word_collaboration_events_pkey";

alter table "public"."word_collaboration_sessions" add constraint "word_collaboration_sessions_pkey" PRIMARY KEY using index "word_collaboration_sessions_pkey";

alter table "public"."approval_comments" add constraint "approval_comment_document_supervisor_id_fkey" FOREIGN KEY (document_supervisor_id) REFERENCES public.document_supervisors(id) not valid;

alter table "public"."approval_comments" validate constraint "approval_comment_document_supervisor_id_fkey";

alter table "public"."categories" add constraint "categories_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."categories" validate constraint "categories_user_id_fkey";

alter table "public"."document_supervisors" add constraint "document_supervisor_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) not valid;

alter table "public"."document_supervisors" validate constraint "document_supervisor_file_id_fkey";

alter table "public"."document_supervisors" add constraint "document_supervisor_supervisor_id_fkey" FOREIGN KEY (supervisor_id) REFERENCES auth.users(id) not valid;

alter table "public"."document_supervisors" validate constraint "document_supervisor_supervisor_id_fkey";

alter table "public"."file_permissions" add constraint "file_permissions_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) not valid;

alter table "public"."file_permissions" validate constraint "file_permissions_file_id_fkey";

alter table "public"."file_permissions" add constraint "file_permissions_granted_by_fkey" FOREIGN KEY (granted_by) REFERENCES auth.users(id) not valid;

alter table "public"."file_permissions" validate constraint "file_permissions_granted_by_fkey";

alter table "public"."file_permissions" add constraint "file_permissions_granted_to_fkey" FOREIGN KEY (granted_to) REFERENCES auth.users(id) not valid;

alter table "public"."file_permissions" validate constraint "file_permissions_granted_to_fkey";

alter table "public"."file_revisions" add constraint "file_revisions_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE not valid;

alter table "public"."file_revisions" validate constraint "file_revisions_file_id_fkey";

alter table "public"."files" add constraint "files_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."files" validate constraint "files_category_id_fkey";

alter table "public"."files" add constraint "files_folder_id_fkey" FOREIGN KEY (folder_id) REFERENCES public.folders(id) not valid;

alter table "public"."files" validate constraint "files_folder_id_fkey";

alter table "public"."files" add constraint "files_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."files" validate constraint "files_user_id_fkey";

alter table "public"."folder_permissions" add constraint "folder_permissions_folder_id_fkey" FOREIGN KEY (folder_id) REFERENCES public.folders(id) not valid;

alter table "public"."folder_permissions" validate constraint "folder_permissions_folder_id_fkey";

alter table "public"."folder_permissions" add constraint "folder_permissions_granted_by_fkey" FOREIGN KEY (granted_by) REFERENCES auth.users(id) not valid;

alter table "public"."folder_permissions" validate constraint "folder_permissions_granted_by_fkey";

alter table "public"."folder_permissions" add constraint "folder_permissions_granted_to_fkey" FOREIGN KEY (granted_to) REFERENCES auth.users(id) not valid;

alter table "public"."folder_permissions" validate constraint "folder_permissions_granted_to_fkey";

alter table "public"."folders" add constraint "folders_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.folders(id) not valid;

alter table "public"."folders" validate constraint "folders_parent_id_fkey";

alter table "public"."folders" add constraint "folders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."folders" validate constraint "folders_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_home_folder_id_fkey" FOREIGN KEY (home_folder_id) REFERENCES public.folders(id) not valid;

alter table "public"."profiles" validate constraint "profiles_home_folder_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_is_active_check" CHECK ((is_active = (true OR false))) not valid;

alter table "public"."profiles" validate constraint "profiles_is_active_check";

alter table "public"."word_collaboration_documents" add constraint "word_collaboration_documents_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) not valid;

alter table "public"."word_collaboration_documents" validate constraint "word_collaboration_documents_file_id_fkey";

alter table "public"."word_collaboration_documents" add constraint "word_collaboration_documents_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) not valid;

alter table "public"."word_collaboration_documents" validate constraint "word_collaboration_documents_updated_by_fkey";

alter table "public"."word_collaboration_events" add constraint "word_collaboration_events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."word_collaboration_events" validate constraint "word_collaboration_events_created_by_fkey";

alter table "public"."word_collaboration_events" add constraint "word_collaboration_events_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) not valid;

alter table "public"."word_collaboration_events" validate constraint "word_collaboration_events_file_id_fkey";

alter table "public"."word_collaboration_sessions" add constraint "word_collaboration_sessions_file_id_fkey" FOREIGN KEY (file_id) REFERENCES public.files(id) not valid;

alter table "public"."word_collaboration_sessions" validate constraint "word_collaboration_sessions_file_id_fkey";

alter table "public"."word_collaboration_sessions" add constraint "word_collaboration_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."word_collaboration_sessions" validate constraint "word_collaboration_sessions_user_id_fkey";

grant delete on table "public"."approval_comments" to "anon";

grant insert on table "public"."approval_comments" to "anon";

grant references on table "public"."approval_comments" to "anon";

grant select on table "public"."approval_comments" to "anon";

grant trigger on table "public"."approval_comments" to "anon";

grant truncate on table "public"."approval_comments" to "anon";

grant update on table "public"."approval_comments" to "anon";

grant delete on table "public"."approval_comments" to "authenticated";

grant insert on table "public"."approval_comments" to "authenticated";

grant references on table "public"."approval_comments" to "authenticated";

grant select on table "public"."approval_comments" to "authenticated";

grant trigger on table "public"."approval_comments" to "authenticated";

grant truncate on table "public"."approval_comments" to "authenticated";

grant update on table "public"."approval_comments" to "authenticated";

grant delete on table "public"."approval_comments" to "service_role";

grant insert on table "public"."approval_comments" to "service_role";

grant references on table "public"."approval_comments" to "service_role";

grant select on table "public"."approval_comments" to "service_role";

grant trigger on table "public"."approval_comments" to "service_role";

grant truncate on table "public"."approval_comments" to "service_role";

grant update on table "public"."approval_comments" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."document_supervisors" to "anon";

grant insert on table "public"."document_supervisors" to "anon";

grant references on table "public"."document_supervisors" to "anon";

grant select on table "public"."document_supervisors" to "anon";

grant trigger on table "public"."document_supervisors" to "anon";

grant truncate on table "public"."document_supervisors" to "anon";

grant update on table "public"."document_supervisors" to "anon";

grant delete on table "public"."document_supervisors" to "authenticated";

grant insert on table "public"."document_supervisors" to "authenticated";

grant references on table "public"."document_supervisors" to "authenticated";

grant select on table "public"."document_supervisors" to "authenticated";

grant trigger on table "public"."document_supervisors" to "authenticated";

grant truncate on table "public"."document_supervisors" to "authenticated";

grant update on table "public"."document_supervisors" to "authenticated";

grant delete on table "public"."document_supervisors" to "service_role";

grant insert on table "public"."document_supervisors" to "service_role";

grant references on table "public"."document_supervisors" to "service_role";

grant select on table "public"."document_supervisors" to "service_role";

grant trigger on table "public"."document_supervisors" to "service_role";

grant truncate on table "public"."document_supervisors" to "service_role";

grant update on table "public"."document_supervisors" to "service_role";

grant delete on table "public"."file_permissions" to "anon";

grant insert on table "public"."file_permissions" to "anon";

grant references on table "public"."file_permissions" to "anon";

grant select on table "public"."file_permissions" to "anon";

grant trigger on table "public"."file_permissions" to "anon";

grant truncate on table "public"."file_permissions" to "anon";

grant update on table "public"."file_permissions" to "anon";

grant delete on table "public"."file_permissions" to "authenticated";

grant insert on table "public"."file_permissions" to "authenticated";

grant references on table "public"."file_permissions" to "authenticated";

grant select on table "public"."file_permissions" to "authenticated";

grant trigger on table "public"."file_permissions" to "authenticated";

grant truncate on table "public"."file_permissions" to "authenticated";

grant update on table "public"."file_permissions" to "authenticated";

grant delete on table "public"."file_permissions" to "service_role";

grant insert on table "public"."file_permissions" to "service_role";

grant references on table "public"."file_permissions" to "service_role";

grant select on table "public"."file_permissions" to "service_role";

grant trigger on table "public"."file_permissions" to "service_role";

grant truncate on table "public"."file_permissions" to "service_role";

grant update on table "public"."file_permissions" to "service_role";

grant delete on table "public"."file_revisions" to "anon";

grant insert on table "public"."file_revisions" to "anon";

grant references on table "public"."file_revisions" to "anon";

grant select on table "public"."file_revisions" to "anon";

grant trigger on table "public"."file_revisions" to "anon";

grant truncate on table "public"."file_revisions" to "anon";

grant update on table "public"."file_revisions" to "anon";

grant delete on table "public"."file_revisions" to "authenticated";

grant insert on table "public"."file_revisions" to "authenticated";

grant references on table "public"."file_revisions" to "authenticated";

grant select on table "public"."file_revisions" to "authenticated";

grant trigger on table "public"."file_revisions" to "authenticated";

grant truncate on table "public"."file_revisions" to "authenticated";

grant update on table "public"."file_revisions" to "authenticated";

grant delete on table "public"."file_revisions" to "service_role";

grant insert on table "public"."file_revisions" to "service_role";

grant references on table "public"."file_revisions" to "service_role";

grant select on table "public"."file_revisions" to "service_role";

grant trigger on table "public"."file_revisions" to "service_role";

grant truncate on table "public"."file_revisions" to "service_role";

grant update on table "public"."file_revisions" to "service_role";

grant delete on table "public"."files" to "anon";

grant insert on table "public"."files" to "anon";

grant references on table "public"."files" to "anon";

grant select on table "public"."files" to "anon";

grant trigger on table "public"."files" to "anon";

grant truncate on table "public"."files" to "anon";

grant update on table "public"."files" to "anon";

grant delete on table "public"."files" to "authenticated";

grant insert on table "public"."files" to "authenticated";

grant references on table "public"."files" to "authenticated";

grant select on table "public"."files" to "authenticated";

grant trigger on table "public"."files" to "authenticated";

grant truncate on table "public"."files" to "authenticated";

grant update on table "public"."files" to "authenticated";

grant delete on table "public"."files" to "service_role";

grant insert on table "public"."files" to "service_role";

grant references on table "public"."files" to "service_role";

grant select on table "public"."files" to "service_role";

grant trigger on table "public"."files" to "service_role";

grant truncate on table "public"."files" to "service_role";

grant update on table "public"."files" to "service_role";

grant delete on table "public"."folder_permissions" to "anon";

grant insert on table "public"."folder_permissions" to "anon";

grant references on table "public"."folder_permissions" to "anon";

grant select on table "public"."folder_permissions" to "anon";

grant trigger on table "public"."folder_permissions" to "anon";

grant truncate on table "public"."folder_permissions" to "anon";

grant update on table "public"."folder_permissions" to "anon";

grant delete on table "public"."folder_permissions" to "authenticated";

grant insert on table "public"."folder_permissions" to "authenticated";

grant references on table "public"."folder_permissions" to "authenticated";

grant select on table "public"."folder_permissions" to "authenticated";

grant trigger on table "public"."folder_permissions" to "authenticated";

grant truncate on table "public"."folder_permissions" to "authenticated";

grant update on table "public"."folder_permissions" to "authenticated";

grant delete on table "public"."folder_permissions" to "service_role";

grant insert on table "public"."folder_permissions" to "service_role";

grant references on table "public"."folder_permissions" to "service_role";

grant select on table "public"."folder_permissions" to "service_role";

grant trigger on table "public"."folder_permissions" to "service_role";

grant truncate on table "public"."folder_permissions" to "service_role";

grant update on table "public"."folder_permissions" to "service_role";

grant delete on table "public"."folders" to "anon";

grant insert on table "public"."folders" to "anon";

grant references on table "public"."folders" to "anon";

grant select on table "public"."folders" to "anon";

grant trigger on table "public"."folders" to "anon";

grant truncate on table "public"."folders" to "anon";

grant update on table "public"."folders" to "anon";

grant delete on table "public"."folders" to "authenticated";

grant insert on table "public"."folders" to "authenticated";

grant references on table "public"."folders" to "authenticated";

grant select on table "public"."folders" to "authenticated";

grant trigger on table "public"."folders" to "authenticated";

grant truncate on table "public"."folders" to "authenticated";

grant update on table "public"."folders" to "authenticated";

grant delete on table "public"."folders" to "service_role";

grant insert on table "public"."folders" to "service_role";

grant references on table "public"."folders" to "service_role";

grant select on table "public"."folders" to "service_role";

grant trigger on table "public"."folders" to "service_role";

grant truncate on table "public"."folders" to "service_role";

grant update on table "public"."folders" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."word_collaboration_documents" to "anon";

grant insert on table "public"."word_collaboration_documents" to "anon";

grant references on table "public"."word_collaboration_documents" to "anon";

grant select on table "public"."word_collaboration_documents" to "anon";

grant trigger on table "public"."word_collaboration_documents" to "anon";

grant truncate on table "public"."word_collaboration_documents" to "anon";

grant update on table "public"."word_collaboration_documents" to "anon";

grant delete on table "public"."word_collaboration_documents" to "authenticated";

grant insert on table "public"."word_collaboration_documents" to "authenticated";

grant references on table "public"."word_collaboration_documents" to "authenticated";

grant select on table "public"."word_collaboration_documents" to "authenticated";

grant trigger on table "public"."word_collaboration_documents" to "authenticated";

grant truncate on table "public"."word_collaboration_documents" to "authenticated";

grant update on table "public"."word_collaboration_documents" to "authenticated";

grant delete on table "public"."word_collaboration_documents" to "service_role";

grant insert on table "public"."word_collaboration_documents" to "service_role";

grant references on table "public"."word_collaboration_documents" to "service_role";

grant select on table "public"."word_collaboration_documents" to "service_role";

grant trigger on table "public"."word_collaboration_documents" to "service_role";

grant truncate on table "public"."word_collaboration_documents" to "service_role";

grant update on table "public"."word_collaboration_documents" to "service_role";

grant delete on table "public"."word_collaboration_events" to "anon";

grant insert on table "public"."word_collaboration_events" to "anon";

grant references on table "public"."word_collaboration_events" to "anon";

grant select on table "public"."word_collaboration_events" to "anon";

grant trigger on table "public"."word_collaboration_events" to "anon";

grant truncate on table "public"."word_collaboration_events" to "anon";

grant update on table "public"."word_collaboration_events" to "anon";

grant delete on table "public"."word_collaboration_events" to "authenticated";

grant insert on table "public"."word_collaboration_events" to "authenticated";

grant references on table "public"."word_collaboration_events" to "authenticated";

grant select on table "public"."word_collaboration_events" to "authenticated";

grant trigger on table "public"."word_collaboration_events" to "authenticated";

grant truncate on table "public"."word_collaboration_events" to "authenticated";

grant update on table "public"."word_collaboration_events" to "authenticated";

grant delete on table "public"."word_collaboration_events" to "service_role";

grant insert on table "public"."word_collaboration_events" to "service_role";

grant references on table "public"."word_collaboration_events" to "service_role";

grant select on table "public"."word_collaboration_events" to "service_role";

grant trigger on table "public"."word_collaboration_events" to "service_role";

grant truncate on table "public"."word_collaboration_events" to "service_role";

grant update on table "public"."word_collaboration_events" to "service_role";

grant delete on table "public"."word_collaboration_sessions" to "anon";

grant insert on table "public"."word_collaboration_sessions" to "anon";

grant references on table "public"."word_collaboration_sessions" to "anon";

grant select on table "public"."word_collaboration_sessions" to "anon";

grant trigger on table "public"."word_collaboration_sessions" to "anon";

grant truncate on table "public"."word_collaboration_sessions" to "anon";

grant update on table "public"."word_collaboration_sessions" to "anon";

grant delete on table "public"."word_collaboration_sessions" to "authenticated";

grant insert on table "public"."word_collaboration_sessions" to "authenticated";

grant references on table "public"."word_collaboration_sessions" to "authenticated";

grant select on table "public"."word_collaboration_sessions" to "authenticated";

grant trigger on table "public"."word_collaboration_sessions" to "authenticated";

grant truncate on table "public"."word_collaboration_sessions" to "authenticated";

grant update on table "public"."word_collaboration_sessions" to "authenticated";

grant delete on table "public"."word_collaboration_sessions" to "service_role";

grant insert on table "public"."word_collaboration_sessions" to "service_role";

grant references on table "public"."word_collaboration_sessions" to "service_role";

grant select on table "public"."word_collaboration_sessions" to "service_role";

grant trigger on table "public"."word_collaboration_sessions" to "service_role";

grant truncate on table "public"."word_collaboration_sessions" to "service_role";

grant update on table "public"."word_collaboration_sessions" to "service_role";


  create policy "Enable users to view their own data only"
  on "public"."categories"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Give users access"
  on "public"."document_supervisors"
  as permissive
  for select
  to public
using ((supervisor_id = auth.uid()));



  create policy "Owner and grantee manages file permissions"
  on "public"."file_permissions"
  as permissive
  for select
  to public
using (((granted_to = auth.uid()) OR (granted_by = auth.uid())));



  create policy "Enable insert for users based on user_id"
  on "public"."files"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to update their own data"
  on "public"."files"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Enable users to view their own data only"
  on "public"."files"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "files insert owner or folder write"
  on "public"."files"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.folder_permissions fperm
  WHERE ((fperm.folder_id = files.folder_id) AND (fperm.granted_to = auth.uid()) AND (fperm.is_active = true) AND ((fperm.permission_type)::text = 'write'::text)))));



  create policy "files select own or shared read write"
  on "public"."files"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.file_permissions fp
  WHERE ((fp.file_id = files.id) AND (fp.granted_to = auth.uid()) AND (fp.is_active = true) AND ((fp.permission_type)::text = ANY ((ARRAY['read'::character varying, 'write'::character varying])::text[]))))));



  create policy "Grantee sees own folder permissions"
  on "public"."folder_permissions"
  as permissive
  for select
  to public
using ((granted_to = auth.uid()));



  create policy "Owner manages folder permissions"
  on "public"."folder_permissions"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.folders
  WHERE ((folders.id = folder_permissions.folder_id) AND (folders.user_id = auth.uid())))));



  create policy "Enable insert for users based on user_id"
  on "public"."folders"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to update their own data"
  on "public"."folders"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Enable users to view their own data only"
  on "public"."folders"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable users to view their own data only"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable users to insert documents 1cqvdzs_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'Documents'::text) AND (((auth.uid())::text = (storage.foldername(name))[1]) OR (EXISTS ( SELECT 1
   FROM public.document_supervisors ds
  WHERE ((ds.supervisor_id = auth.uid()) AND ((ds.status)::text = 'accepted'::text) AND (POSITION(((ds.file_id)::text) IN (objects.name)) > 0)))))));



  create policy "Enable users to select documents 1cqvdzs_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Documents'::text) AND (((auth.uid())::text = (storage.foldername(name))[1]) OR (EXISTS ( SELECT 1
   FROM public.document_supervisors ds
  WHERE ((ds.supervisor_id = auth.uid()) AND ((ds.status)::text = 'accepted'::text) AND (POSITION(((ds.file_id)::text) IN (objects.name)) > 0)))))));



  create policy "Enable users to update documents 1cqvdzs_0"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'Documents'::text) AND (((auth.uid())::text = (storage.foldername(name))[1]) OR (EXISTS ( SELECT 1
   FROM public.document_supervisors ds
  WHERE ((ds.supervisor_id = auth.uid()) AND ((ds.status)::text = 'accepted'::text) AND (POSITION(((ds.file_id)::text) IN (objects.name)) > 0)))))));



  create policy "Enable users to update documents 1cqvdzs_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Documents'::text) AND (((auth.uid())::text = (storage.foldername(name))[1]) OR (EXISTS ( SELECT 1
   FROM public.document_supervisors ds
  WHERE ((ds.supervisor_id = auth.uid()) AND ((ds.status)::text = 'accepted'::text) AND (POSITION(((ds.file_id)::text) IN (objects.name)) > 0)))))));



  create policy "Give shared user access 1cqvdzs_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Documents'::text) AND (EXISTS ( SELECT 1
   FROM public.file_permissions fp
  WHERE ((fp.granted_to = auth.uid()) AND (fp.is_active = true) AND ((fp.permission_type)::text = ANY ((ARRAY['read'::character varying, 'write'::character varying])::text[])))))));



  create policy "Give users access to own folder 1cqvdzs_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'Documents'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



